FROM python:3.8-slim

WORKDIR /app/usr/src/

COPY . /app/usr/src/Telegram/

RUN pip install -r ./Telegram/requirements.txt
RUN apt-get update & apt-get install


CMD [ "python","./Telegram/RunAll.py" ]
