FROM python:3.8-slim

WORKDIR /app/usr/src/

COPY connection.py /app/usr/src/Connection/
COPY requirements.txt /app/usr/src/Connection/

RUN pip install -r requirements.txt
RUN apt-get update & apt-get install

CMD [ "python","./Connection/connection.py" ]
